import Header from '@/app/Component/Header'
import './globals.css'
import Header2 from '@/app/Component/Header2'
import Newsletter from '@/app/Component/Newsletter'
import Footer from '@/app/Component/Footer'
import Homeheader from './Component/Homeheader'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header/>
        {children}
       <Newsletter/>
       <Footer/></body>
    </html>
  )
}
